"""empty message

Revision ID: d8fbac201576
Revises: fd78d6117c78
Create Date: 2019-09-30 10:20:02.642559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fbac201576'
down_revision = 'fd78d6117c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('youtube_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'youtube_id')
    # ### end Alembic commands ###
